run('demo_channelm.m')
disp('!!!!!demo_channelm done!!!!!')
disp('****************************')
pause(2)
run('demo_getCutout.m')
disp('!!!!!demo_getCutout done!!!!!')
disp('****************************')
pause(2)
run('demo_mhdm.m')
disp('!!!!!demo_mhdm done!!!!!')
disp('****************************')
pause(2)
run('demo_mixingm.m')
disp('!!!!!demo_mixingm done!!!!!')
disp('****************************')
pause(2)
run('demo_rotstrat.m')
disp('!!!!!demo_rotstrat done!!!!!')
disp('****************************')
pause(2)
run('demo_transition_bl.m')
disp('!!!!!demo_transition_bl done!!!!!')
disp('****************************')
pause(2)
run('demo_turbm.m')
disp('!!!!!demo_turbm done!!!!!')
disp('****************************')
pause(2)
close all