run('DEMO_channelm.m')
disp('!!!!!DEMO_channelm done!!!!!')
disp('****************************')
pause(2)
run('DEMO_getCutout.m')
disp('!!!!!DEMO_getCutout done!!!!!')
disp('****************************')
pause(2)
run('DEMO_mhdm.m')
disp('!!!!!DEMO_mhdm done!!!!!')
disp('****************************')
pause(2)
run('DEMO_mixingm.m')
disp('!!!!!DEMO_mixingm done!!!!!')
disp('****************************')
pause(2)
run('DEMO_rotstrat.m')
disp('!!!!!DEMO_rotstrat done!!!!!')
disp('****************************')
pause(2)
run('DEMO_transition_bl.m')
disp('!!!!!DEMO_transition_bl done!!!!!')
disp('****************************')
pause(2)
run('DEMO_turbm.m')
disp('!!!!!DEMO_turbm done!!!!!')
disp('****************************')
pause(2)
close all