function GetBoxFilterPressureResult = GetBoxFilterPressure(obj,authToken,dataset,time,filterlength,nlayers,temporalInterpolation,points)
%GetBoxFilterPressure(obj,authToken,dataset,time,filterlength,nlayers,temporalInterpolation,points)
%
%   BoxFilterForPressure
%   
%     Input:
%       authToken = (string)
%       dataset = (string)
%       time = (float)
%       filterlength = (float)
%       nlayers = (int)
%       temporalInterpolation = (TemporalInterpolation)
%       points = (ArrayOfPoint3)
%   
%     Output:
%       GetBoxFilterPressureResult = (ArrayOfFloat)

% Build up the argument lists.
values = { ...
   authToken, ...
   dataset, ...
   time, ...
   filterlength, ...
   nlayers, ...
   temporalInterpolation, ...
   points, ...
   };
names = { ...
   'authToken', ...
   'dataset', ...
   'time', ...
   'filterlength', ...
   'nlayers', ...
   'temporalInterpolation', ...
   'points', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://turbulence.pha.jhu.edu/}TemporalInterpolation', ...
   '{http://turbulence.pha.jhu.edu/}ArrayOfPoint3', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://turbulence.pha.jhu.edu/', ...
    'GetBoxFilterPressure', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://turbulence.pha.jhu.edu/GetBoxFilterPressure', ...
    soapMessage);
GetBoxFilterPressureResult = parseSoapResponse(response);
