function GetPositionInertialParticleResult = GetPositionInertialParticle(obj,authToken,dataset,StartTime,EndTime,Tp,spatialInterpolation,points,InitialV)
%GetPositionInertialParticle(obj,authToken,dataset,StartTime,EndTime,Tp,spatialInterpolation,points,InitialV)
%
%   [UNDER DEVELOPMENT] GetPositionInertialParticle
%   
%     Input:
%       authToken = (string)
%       dataset = (string)
%       StartTime = (float)
%       EndTime = (float)
%       Tp = (float)
%       spatialInterpolation = (SpatialInterpolation)
%       points = (ArrayOfPoint3)
%       InitialV = (ArrayOfVector3)
%   
%     Output:
%       GetPositionInertialParticleResult = (ArrayOfPoint3)

% Build up the argument lists.
values = { ...
   authToken, ...
   dataset, ...
   StartTime, ...
   EndTime, ...
   Tp, ...
   spatialInterpolation, ...
   points, ...
   InitialV, ...
   };
names = { ...
   'authToken', ...
   'dataset', ...
   'StartTime', ...
   'EndTime', ...
   'Tp', ...
   'spatialInterpolation', ...
   'points', ...
   'InitialV', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://turbulence.pha.jhu.edu/}SpatialInterpolation', ...
   '{http://turbulence.pha.jhu.edu/}ArrayOfPoint3', ...
   '{http://turbulence.pha.jhu.edu/}ArrayOfVector3', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://turbulence.pha.jhu.edu/', ...
    'GetPositionInertialParticle', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://turbulence.pha.jhu.edu/GetPositionInertialParticle', ...
    soapMessage);
GetPositionInertialParticleResult = parseSoapResponse(response);
