function NullOpResult = NullOp(obj,authToken,points)
%NullOp(obj,authToken,points)
%
%   Perform a null operation -- for testing throughput
%   
%     Input:
%       authToken = (string)
%       points = (ArrayOfPoint3)
%   
%     Output:
%       NullOpResult = (ArrayOfVector3)

% Build up the argument lists.
values = { ...
   authToken, ...
   points, ...
   };
names = { ...
   'authToken', ...
   'points', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://turbulence.pha.jhu.edu/}ArrayOfPoint3', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://turbulence.pha.jhu.edu/', ...
    'NullOp', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://turbulence.pha.jhu.edu/NullOp', ...
    soapMessage);
NullOpResult = parseSoapResponse(response);
